- name: Install Docker-PY
  pip:
    name: "{{ item }}"
  with_items:
    - six==1.4.1
    - docker-py==1.1.0
  sudo: yes

- name: Create Pure FSM Mysql container
  docker:
    name: pure-mysql
    image: mysql
    state: started
    ports:
        - "3306:3306"
    env:
      MYSQL_ROOT_PASSWORD: purefsm
      MYSQL_DATABASE: purefsm
    volumes:
      - /data
