- name: Install Docker-PY
  pip:
    name: "{{ item }}"
  with_items:
    - six==1.4.1
    - docker-py==1.1.0

- name: Init Boot2docker VM
  command: "boot2docker {{ item }}"
  with_items:
    - start
    - shellinit

#- name: Remove Pure FSM Mysql existing container
#  docker:
#    name: pure-mysql
#    image: mysql
#    state: absent
#    use_tls: encrypt
#    tls_hostname: boot2docker

- name: Create Pure FSM Mysql container
  environment:
        DOCKER_HOST: tcp://192.168.59.103:2376
        DOCKER_CERT_PATH: /Users/keithh/.boot2docker/certs/boot2docker-vm
        DOCKER_TLS_VERIFY: 1
  docker:
    name: pure-mysql
    image: mysql
    state: started
    use_tls: encrypt
    tls_hostname: boot2docker
    ports:
        - "3306:3306"
    env:
      MYSQL_ROOT_PASSWORD: purefsm
      MYSQL_DATABASE: purefsm
    volumes:
      - /data
