language: java
sudo: required

os:
  - linux

env:
- ANSIBLE_HOST_KEY_CHECKING=False

jdk:
  - oraclejdk8
  
before_install:
  - sudo apt-get install docker-engine

  - sudo pip install --upgrade pip
  - sudo pip install ansible
  - sudo pip install docker-py

install:
  - ansible-playbook -v --inventory-file=./fsm-repository-mysql/src/main/environment/inv_travis ./fsm-repository-mysql/src/main/environment/site.yml
