language: java
sudo: required

jdk:
  - oraclejdk8
  
services:
  - docker
  
before_install:
  - sudo apt-get -y install software-properties-common
  - sudo apt-add-repository -y ppa:ansible/ansible-1.9
  - sudo apt-get update
  - sudo apt-get -y install ansible
  
script: ansible-playbook -v $TRAVIS_BUILD_DIR/PureFSM/fsm-repository-mysql/src/main/environment/main.yml
