language: java
sudo: required

jdk:
  - oraclejdk8
  
services:
  - docker
  
before_install:
  - sudo apt-get -y install software-properties-common
  - sudo apt-add-repository -y ppa:ansible/ansible
  - sudo apt-get update
  - sudo apt-get -y install ansible
  - ansible-playbook -v $TRAVIS_BUILD_DIR/fsm-repository-mysql/src/main/environment/main.yml
  
script: ./gradlew clean build
