language: java
sudo: required

jdk:
  - oraclejdk8
  
services:
  - docker
  
before_install:
  - sudo pip install --upgrade pip
  - sudo pip install ansible
  
install:
  - ansible-playbook -v ./fsm-repository-mysql/src/main/environment/main.yml
