language: java
sudo: required

jdk:
  - oraclejdk8
  
services:
  - docker
  
before_install:
  - pip install --upgrade pip
  - pip install ansible
  
install:
  - ansible-playbook -v $TRAVIS_BUILD_DIR/PureFSM/fsm-repository-mysql/src/main/environment/main.yml
