language: java
sudo: required

os:
  - linux

env:
- ANSIBLE_HOST_KEY_CHECKING=False

jdk:
  - oraclejdk8
  
services:
  - docker
  
before_install:
  - sudo pip install --upgrade pip
  - sudo pip install ansible
  
install:
  - ansible-playbook -v --inventory-file=./fsm-repository-mysql/src/main/environment/inv_travis ./fsm-repository-mysql/src/main/environment/site.yml
