language: java
sudo: required
dist: trusty

env:
- ANSIBLE_HOST_KEY_CHECKING=False

jdk:
  - oraclejdk8

services:
  - docker

addons:
  hosts:
    - mysql-purefsm

before_install:
  - sudo pip install --upgrade pip
  - sudo pip install ansible
  - sudo pip install docker-py

install:
  - ansible-playbook -v --inventory-file=./fsm-repository-mysql/src/main/environment/inv_travis ./fsm-repository-mysql/src/main/environment/site.yml

script: ./gradlew clean build