- name: install pip
  easy_install: name=pip state=latest

- name: update yum
  yum: name=* state=latest

- name: register docker yum repo
  template: src=../templates/docker.repo.j2 dest=/etc/yum.repos.d/docker.repo

- name: install docker
  yum: name=docker-engine

- name: start docker
  command: service docker start

- name: add user to docker group
  command: usermod -aG docker vagrant

- name: install docker-py
  pip: name="{{ item }}"
  with_items:
    - six
    - docker-py