
- name: create pure-fsm mysql container
  docker_container:
    api_version: "1.20"
    hostname: mysql-purefsm
    name: mysql-purefsm
    image: mysql
    state: started
    ports:
        - "3306:3306"
    env:
      MYSQL_ROOT_PASSWORD: purefsm
      MYSQL_DATABASE: purefsm